### PR TITLE
I'm bad at git

### PR DESCRIPTION
**Pull request by bond15**
manually adopting changes

### CODE REVIEW

**Comment by bond15** [comment]
Ah DialSets still needs to be renamed..

**Comment by bond15** [comment]
TODO: still need to use the `pos` and `dir` naming conventions

**Review by vcvpaiva — APPROVED** [review]

**Review by vcvpaiva — APPROVED** [review]

**Comment by vcvpaiva** [comment]
this file still only has compat' on the left. we need it on the right too, I believe.

**Comment by bond15** [comment]
> 
Referring to `Lineale.agda` correct?

So instead of the monoidal proset definition having 
`symm : ∀{a b : P} → a ⊙ b ≡ b ⊙ a`
there would be left and right `compat` laws?
```
   compatʳ : ∀{a b : P} → rel a b → (∀{c : P} → (rel (a ⊙ c) (b ⊙ c)))
   compatˡ : ∀{a b : P} → rel a b → (∀{c : P} → (rel (c ⊙ a) (c ⊙ b)))
 ```

**Comment by vcvpaiva** [comment]
well, yes, the two compat's make ⊙ a bifunctor, it does not need to be symmetric. 

in our case the tensor is symmetric, so I believe we should keep the line

symm : ∀{a b : P} → a ⊙ b ≡ b ⊙ a

but in proofs we should use bifunctoriality as much as possible, symmetry only when  we have it, like in Two.

**Pull request merged**
